AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  LLMServiceUrl:
    Type: String
    Description: URL for the LLM microservice
Resources:
  BackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST,OPTIONS'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
        AllowOrigin: '''*'''
    Metadata:
      SamResourceId: BackendApi
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: provided.al2
      CodeUri: s3://metis-backend-w8ej736hj9/d8ffbf5e6b507cd26d9f6da29ec50d1f
      MemorySize: 128
      Timeout: 600
      Environment:
        Variables:
          LLM_MICROSERVICE_URL:
            Ref: LLMServiceUrl
      Events:
        ExplainApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: BackendApi
            Path: /api/explain
            Method: POST
        OptionsApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: BackendApi
            Path: /api/explain
            Method: OPTIONS
    Metadata:
      SamResourceId: BackendFunction
Outputs:
  BackendApiUrl:
    Description: API Gateway endpoint URL for the backend
    Value:
      Fn::Sub: https://${BackendApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/explain
