AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  LLMServiceUrl:
    Type: String
    Description: URL for the LLM microservice

Resources:
  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: provided.al2
      CodeUri: ./
      MemorySize: 128
      Timeout: 900
      Environment:
        Variables:
          LLM_MICROSERVICE_URL: !Ref LLMServiceUrl
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - POST
          AllowHeaders:
            - Content-Type

Outputs:
  BackendFunctionUrl:
    Description: "Backend Function URL"
    Value: !GetAtt BackendFunction.FunctionUrl