AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  LLMServiceUrl:
    Type: String
    Description: URL for the LLM microservice

Resources:
  BackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: provided.al2
      CodeUri: ./
      MemorySize: 128
      Timeout: 600
      Environment:
        Variables:
          LLM_MICROSERVICE_URL: !Ref LLMServiceUrl
      Events:
        ExplainApi:
          Type: Api
          Properties:
            RestApiId: !Ref BackendApi
            Path: /api/explain
            Method: POST
        OptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref BackendApi
            Path: /api/explain
            Method: OPTIONS

Outputs:
  BackendApiUrl:
    Description: "API Gateway endpoint URL for the backend"
    Value: !Sub "https://${BackendApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/explain"