service: microservices

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

functions:
  llm:
    handler: app.lambda_handler
    events:
      - http:
          path: microservices/llm
          method: post
    environment:
      PYTHONPATH: ./
      OPENAI_API_KEY: ${env:OPENAI_API_KEY}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**
    - venv/**
  include:
    - app.py
    - handlers/**