AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Metis Microservices

Globals:
  Function:
    Timeout: 900
    Runtime: python3.9

Resources:
  LLMFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: llm/
      Handler: app.lambda_handler
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - '*'
          AllowMethods:
            - POST
          AllowHeaders:
            - Content-Type
      Environment:
        Variables:
          PYTHONPATH: ./
          OPENAI_API_KEY: !Ref OpenAIApiKey
    Metadata:
      BuildMethod: python3.9

Parameters:
  OpenAIApiKey:
    Type: String
    Description: OpenAI API Key
    NoEcho: true

Outputs:
  LLMFunctionUrl:
    Description: "LLM Function URL"
    Value: !GetAtt LLMFunction.FunctionUrl